name: Test Flask App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Display Python version
      run: python --version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install dependencies directly from requirements.txt
        pip install -r app/requirements.txt
        # Print installed packages for debugging
        pip list

    - name: Debug environment
      run: |
        echo "Current directory: $(pwd)"
        ls -la app/
        ls -la app/tests/

    - name: Run pytest with verbose output
      run: |
        cd app
        python -m pytest -vv --no-header

    - name: Test app startup
      run: |
        cd app
        # Start the Flask app in the background
        python app.py &
        APP_PID=$!
        # Give the app a moment to start
        sleep 5
        # Check if the app is responding
        curl -f http://localhost:5000/ || exit 1
        # Kill the app
        kill $APP_PID