name: Test Flask App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install explicitly mentioned packages first
        python -m pip install Flask==2.0.0 Werkzeug==2.0.0 pytest==7.4.0
        # Then install any additional packages from requirements.txt
        if [ -f app/requirements.txt ]; then pip install -r app/requirements.txt; fi

    - name: Run pytest
      run: |
        cd app
        # Adding verbose output to see more details about test execution
        python -m pytest tests/ -v

    - name: Test app startup
      run: |
        cd app
        # Start the Flask app in the background
        python app.py &
        # Give the app a moment to start
        sleep 5
        # Check if the app is responding
        curl -f http://localhost:5000/ || exit 1
        # Kill the app
        kill $(lsof -t -i:5000)